/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VgfiitAmbulanceWlList {
    }
}
declare global {
    interface HTMLVgfiitAmbulanceWlListElement extends Components.VgfiitAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLVgfiitAmbulanceWlListElement: {
        prototype: HTMLVgfiitAmbulanceWlListElement;
        new (): HTMLVgfiitAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "vgfiit-ambulance-wl-list": HTMLVgfiitAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface VgfiitAmbulanceWlList {
    }
    interface IntrinsicElements {
        "vgfiit-ambulance-wl-list": VgfiitAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vgfiit-ambulance-wl-list": LocalJSX.IntrinsicElements["vgfiit-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLVgfiitAmbulanceWlListElement>;
        }
    }
}
